### ISSUE TITLE
List indexes in keypath?

### ISSUE THREAD

**Issue by tadams42** [fabiocaccamo/python-benedict#1]
Hi there, I'm loving `benedict`, but have a feature request... Can we have something like this:

```Python
from benedict import benedict

d = benedict({
    "a": [
        {"b": 42}, 
        {"b": 24}
    ]
})
d.get("a.1.b")
=> 24
```

**Comment by fabiocaccamo** [comment]
Thank you, I’m glad you like it.
This is a very good idea, I will implement it as soon as possible.

**Comment by fabiocaccamo** [comment]
@tadams42 which syntax do you think is better?
```python
d.get("a.1.b")
```
or
```python
d.get("a[1].b")
```

**Comment by tadams42** [comment]
Hi, sorry for late reply...

I like `d.get("a.1.b")` better since it is less chars to type :-)

**Comment by supersational** [comment]
I love this library for dealing with nested JSON data from web APIs (sometimes the JSON can be massive), just copy the paths into a benedict.

 `d = benedict(response.json())` 

One easy way to get the path in Chrome network tab at least, is to right click and press "Copy property path", I've attached a screenshot below
![image](https://user-images.githubusercontent.com/11251397/73008507-9d6b4400-3e06-11ea-8ca9-49b767be484f.png)

In this instance the path is `icons[2].src`, it would be great if this was supported by benedict :) although the other syntax is shorter and could also be used.

Also for larger structures this method can return odd double-quoting in paths, e.g. `products[""0""].categories[1].name` .. ugly syntax but in my case would be great if that also worked seamlessly with benedict!

**Comment by d4n13lbc** [comment]
I see this was implemented, but jsondiff returns integer as keys. With the current solution it is not possible to index by an integer key

**Comment by fabiocaccamo** [comment]
@d4n13lbc don'worry, I will implement the a flexible solution.

**Comment by fabiocaccamo** [comment]
@tadams42, @supersational, @d4n13lbc you can install `0.16.0` version. 

List index support in keypaths has been implemented using the standard array syntax, eg: `products[0].categories[1].name`.

Let me know if you find any issue or you need new features.

**Comment by d4n13lbc** [comment]
Probably not the best place or the best example, but maybe this is worthy for
somebody

```
data = benedict({'my_key': {1: {2: {'other_key': 'other_value'}}}})
>>> 'my_key[1]' in data
True
>>> 'my_key[1][2]' in data
True
```

```
data = benedict({'my_key': {'1': [{'a': 'b'}]}})
>>> 'my_key.1' in data
True
>>> 'my_key.1[0]' in data
True
```

Notice the use of [] for integer key and . for string key
