### ISSUE TITLE
Internal benedict reference to old value

### ISSUE THREAD

**Issue by kikohs** [fabiocaccamo/python-benedict#102]
I've opened an issue on ORJSON which I'm using to serialize benedict dicts.
https://github.com/ijl/orjson/issues/281

Basically I don't understand why something like this could happen:

```python
from benedict import benedict
import orjson

d = benedict({
    "internal": benedict({
        "mykey": "OLD"
    })
})

d['internal'] = benedict({
    "mykey": "NEW"
})

res = orjson.dumps(d)
print(res)
```

```b'{"internal":{"mykey":"OLD"}}'```

It should be "NEW". 
Could you please explain how benedict handles sub benedict references?

Or why this would happen, thank you.

**Comment by fabiocaccamo** [comment]
@kikohs thank you for reporting this, I will add a test case as soon as possible.

**Comment by fabiocaccamo** [comment]
@kikohs you can upgrade to `0.25.2` version.
