### ISSUE TITLE
setting value of dict element inside a list

### ISSUE THREAD

**Issue by ponders** [fabiocaccamo/python-benedict#109]
should this work?

```
d = benedict()
d['a'] = '1'
d['b[1]'] = 'quote'
d['c.d[3]'] = 'mote'
d['e.f[4].g'] = 'note'
```

The last line `d['e.f[4].g'] = 'note'` throws an exception

**Comment by fabiocaccamo** [comment]
@ponders thank you for reporting this, you can upgrade to `0.25.3` version.

**Comment by ponders** [comment]
Thanks, @fabiocaccamo! That's working great for me.
