### ISSUE TITLE
[Question] Can I use [n] as a way to loop through all in list?

### ISSUE THREAD

**Issue by simkimsia** [fabiocaccamo/python-benedict#11]
```python
In [1]:from benedict import benedict

In [2]: test = {"lorem": [{"ipsum":"a"}, {"ipsum": "b"}]}

In [3]: benedict_test = benedict(test)

In [4]: result = benedict_test.get("lorem[0].ipsum")

In [5]: result
Out[5]: 'a'

In [6]: result = benedict_test.get("lorem[n].ipsum")

In [7]: result
```

I guess the answer to my question is a simple no.

But I was wondering if there's a way to get what I want? Either via a feature request or via other pythonic code to work with existing benedict?

Expected output is a list of `['a', 'b']`

**Comment by fabiocaccamo** [comment]
@simkimsia actually it's not possible, but it is already on my TODO to support `*` as index.

```python
from benedict import benedict

test = benedict({"lorem": [{"ipsum":"a"}, {"ipsum": "b"}]})
lorem_ipsum_list = test['lorem[*]']
print(lorem_ipsum_list) # -> ["a", "b"]
```

**Comment by simkimsia** [comment]
> The problem is

I'm okay with that problem.

By the way, I am writing my own utility method to do something like this in my Django app until this is covered in benedict. 

And my default if the keypath after the `[*]` is not found, then I simply skip.

Not sure what your thoughts are regarding this

**Comment by fabiocaccamo** [comment]
@simkimsia I updated my previous comment.
If you can, paste here your own utility method to do this.

**Comment by simkimsia** [comment]
my utility method is kinda 💩 and it's a bit different in the sense that I want to return a dictionary of keypaths to list_of_values

and it's not tested yet

```python

def loop_thru_list_of_dict_n_extract(list_of_dicts, list_of_keypaths):
    """
    expect to use benedict library
    if keypath not found, simply skip to next dict
    the keypaths are in string or array
    return a dict where the keys are the keypaths and the values are the lists of found values
    """
    return_dict = {}

    for keypath in list_of_keypaths:
        return_dict[keypath] = []
    for dic in list_of_dicts:
        dic_benedict = benedict(dic)
        for keypath in list_of_keypaths:
            found_value = dic_benedict.get(keypath, None)
            if found_value is None:
                continue
            return_dict[keypath].append(found_value)
    return return_dict
```

How i intend to call it
```python
pm_loop_dict = loop_thru_list_of_dict_n_extract(
            quotation_cached_approvers_dict["Project Manager"], ["signum", "name"]
        )
        row_data["Approval_L1"] = ";".join(pm_loop_dict["signum"])
        row_data["Approval_L1_Name"] = ";".join(pm_loop_dict["name"])
```

SOrry I didn't have time to clean this up.

**Comment by fabiocaccamo** [comment]
With `0.21.0` version you can do: 
```python
from benedict import benedict

test = benedict({"lorem": [{"ipsum":"a"}, {"ipsum": "b"}]})
lorem_ipsum_list = test.match('lorem[*].ipsum')
print(lorem_ipsum_list) # -> ["a", "b"]
```

**Comment by simkimsia** [comment]
I will test this on saturday. Thank you @fabiocaccamo

**Comment by simkimsia** [comment]
Thank you @fabiocaccamo it works as expected.. I am going to deprecate my original hackish method
