### ISSUE TITLE
Return type(self) from _cast and __deepcopy__ methods

### ISSUE THREAD

**Issue by FilippoLippi** [fabiocaccamo/python-benedict#115]
To be able to subclass benedict without redefining _cast and __deepcopy__ 
it would be nice if these methods return instances of class type(self) instead of class benedict

**Comment by fabiocaccamo** [comment]
@FilippoLippi you can upgrade to `0.27.0` version.

**Comment by FilippoLippi** [comment]
thanks @fabiocaccamo
