### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by hagfelsh** [fabiocaccamo/python-benedict#14]
**Python version**
3.6.9

**Package version**
0.18.1

**Current behavior (bug description)**
on the very first line where i call the benedict() class, an exception is thrown:

```
Traceback (most recent call last):
  File "benedict-test.py", line 18, in <module>
    d = benedict()
TypeError: 'module' object is not callable

```
This even happens when creating a dictionary just as your usage examples demonstrate.

**Expected behavior**
see above!

**Comment by fabiocaccamo** [comment]
Check how you import it.

**Comment by hagfelsh** [comment]
I did originally have that mistake, yes! However here's the whole file: (the traceback is the same of course)

```
from benedict import benedict

d = benedict()
d['profile', 'firstname'] = 'Fabio'
print(d)
```

**Comment by fabiocaccamo** [comment]
I don’t think the traceback is the same, could you check it please?

**Comment by hagfelsh** [comment]
Sure thing!
```
Traceback (most recent call last):
  File "/home/hagfelsh/.PyCharmCE2019.3/config/scratches/benedict-test.py", line 3, in <module>
    d = benedict()
TypeError: 'module' object is not callable

Process finished with exit code 1
```
In pycharm there are some deeper parts of the traceback. I'm new to python so I'm not sure what in here is valuable.  Here are some that look like they might be:

```
exception/type/args = {getset_descriptor} <attribute 'args' of 'BaseException' objects>

traceback_frame/stack[4] = 'frame: <module> [pydevd.py:2127]  id:35889816'
```

**Comment by fabiocaccamo** [comment]
I don't think this is a library problem, this snipped of code works perfectly:
```python
from benedict import benedict

d = benedict()
d['profile', 'firstname'] = 'Fabio'
print(d)
```
and prints:
```python
{'profile': {'firstname': 'Fabio'}}
```

**Comment by hagfelsh** [comment]
Well that's interesting!  I wonder what's wrong in my environment!  I'll cook up a new venv and try it there.  Thanks for such fast responses :)

**Comment by fabiocaccamo** [comment]
Ok, don't worry! I you find any bug please provide also a failing test case to speed up bug fixing.

**Comment by flutterq** [comment]
[All possible working solution at [Solved] TypeError: ‘module’ object is not callable
](https://flutterq.com/typeerror-module-object-is-not-callable/)

**Comment by mthbrown** [comment]
In case anyone runs into this in the future, this is probably due to you installing the wrong **benedict** module. Instead of:

```
pip install benedict
```

you should run:

```
pip install python-benedict
```

**Comment by fabiocaccamo** [comment]
@mthbrown thanks for clarifying the issue, it will surely be useful to someone else.
