### ISSUE TITLE
Bug: Benedict to_json converts np.int64 to str

### ISSUE THREAD

**Issue by divyanshu16** [fabiocaccamo/python-benedict#15]
Whenever np.int64 datatype comes, benedict is returning str due to which when I json load, I am not seeing number.

`json.loads(benedict({"x": [np.int64(0), np.int64(34)]}).to_json())`

**Comment by fabiocaccamo** [comment]
@divyanshu16 as you can see in the [json serializer](https://github.com/fabiocaccamo/python-benedict/blob/master/benedict/serializers/json.py#L34), all unexpected types are casted to `str` to avoid encoding errors.

Does it work correctly if you encode it with the standard `json` encoder?
```python
json.loads(json.dumps({"x": [np.int64(0), np.int64(34)]})))
```

Keep in mind that in `benedict` all encoders/decoders can receive their own options passed using kwargs, it means that you can write your own json encoder and [pass it](https://github.com/fabiocaccamo/python-benedict#to_json) using the `default` option to `to_json` method.

**Comment by fabiocaccamo** [comment]
any feedback?

**Comment by divyanshu16** [comment]
Encoder from https://stackoverflow.com/a/47626762/3234468 helps in json load and then applying deep merge using benedict worked for me.
