### ISSUE TITLE
Reduce dependencies via separate package?

### ISSUE THREAD

**Issue by braco** [fabiocaccamo/python-benedict#18]
Hi, have you given any thought to separating the core dictionary traversal/manipulation extensions into its own package? We were surprised that the dependencies included things as far reaching as url fetching, the IO featureset, etc.

**Comment by fabiocaccamo** [comment]
@braco this is an interesting topic. I already taken in consideration what you suggested, it will be surely the right approach, but frankly I'm really happy when I do complex operations such as IO operations > manipulation > IO operations again with just 1 import statement and 3 lines of code.

I understand also that most of the dependencies are related to the IO features and if you don't need IO operations at all there is no reason to install them. 
A possible solution could be to add support to `extras_require` and make the library working even without IO dependencies (except the IO methods, obviously), in this way in the installation phase we could do:
-   `pip install python-benedict` *(install the core library and keypath)*
-   `pip install python-benedict[io]` *(install the IO dependencies)*

**Comment by braco** [comment]
That sounds like a good idea to me. This is anecdotal but our back end engineer was resistant to use your library because of all of the extra dependencies. Would be really cool to see a zero third party dependency package if that's possible. You have a lot of great utility in the core methods.

**Comment by fabiocaccamo** [comment]
Remove all the dependencies is not possible, in any case all the deps used are known and well tested.

**Comment by fabiocaccamo** [comment]
@braco maybe that with the time I will move some parts of this library to their own library, but this package will continue to install everything it needs at once, for this reason I decided to close this issue.
