### ISSUE TITLE
Opening json file

### ISSUE THREAD

**Issue by algaspar** [fabiocaccamo/python-benedict#19]
I'm presuming that this is just a usage issue rather than a bug.

I have a json formatted file in a local folder (windows 10) containing a json array of several json objects.  I was testing python-benedict functionality.  If I open the file like this:

    with open('filename.json', 'r', encoding='utf-8) as opened_file:
         loaded_file = json.load(opened_file)

'loaded_file' is returned as a list of dicts, and I can perform 'd = benedict(loaded__file[0])' and then run benedict utilities against 'd'.

On the other hand, I was trying to save a step and do d = benedict('filename.json').  When I do that (in an ipython shell), I get "ValueError: Invalid string data input."

Suggestions?

Thanks--

--Al

**Comment by fabiocaccamo** [comment]
@algaspar thank you for reporting this, could you attach your json file here please?

**Comment by algaspar** [comment]
Here's a test file that I was using...
[json_results.txt](https://github.com/fabiocaccamo/python-benedict/files/5052116/json_results.txt)

Thanks--

Al

**Comment by algaspar** [comment]
FYI.  This was on a Windows 10 Pro box running Python 3.7.3 with python-benedict 0.18.1 and iPython 7.6.0.

--Al

**Comment by fabiocaccamo** [comment]
Fixed in `0.18.2` version.
