### ISSUE TITLE
Separate installation targets for certain dependencies 

### ISSUE THREAD

**Issue by totalhack** [fabiocaccamo/python-benedict#200]
Hey there, this looks like a really useful utility. Just a recommendation -- the base install may be kept more lightweight if you made some separate install targets for certain features. For example, a `pip install python-benedict[s3]` option that would pull in boto.

**Comment by gschoenberger** [comment]
That would be really great!
We are using benedicts a lot but have no need for any s3 functionalities.
Moreover we are compiling our code with nuitka. Unfortunately pip install comes with a lot of dependencies now:
Installing collected packages: text-unidecode, python-fsutil, phonenumbers, mailchecker, xmltodict, xlrd, toml, six, pyyaml, python-slugify, jmespath, ftfy, et-xmlfile, python-dateutil, openpyxl, botocore, s3transfer, boto3, python-benedict

As a consequence standalone compiling with nuitka takes a lot of time.
Any chance to get a separate install target for certain features soon?

THX, Georg

**Comment by fabiocaccamo** [comment]
Hi @gschoenberger 
I agree, and now this has become a priority due to the number of features/dependencies.

This will be available soon ;)

**Comment by fabiocaccamo** [comment]
@gschoenberger @totalhack do you think is enough to separate only `s3` and `xls`?

**Comment by totalhack** [comment]
Tough to know where to draw the line on something like this since every person's use case may be different. Start with the low hanging fruit. Can always rip out more later if issues arise.

**Comment by gschoenberger** [comment]
> @gschoenberger @totalhack do you think is enough to separate only `s3` and `xls`?

For me, yes!

**Comment by fabiocaccamo** [comment]
@totalhack @gschoenberger Added support to optional requirements in `0.29.0` version: 

https://github.com/fabiocaccamo/python-benedict#optional-requirements
