### ISSUE TITLE
Add a method that tries different key paths and returns the first truthy value or the last one

### ISSUE THREAD

**Issue by emanuelmd** [fabiocaccamo/python-benedict#23]
Hello, awesome library you got here, I thoroughly enjoyed the pun as well.

Working with it made me realize of another functionality that could be built in, namely trying a list of keypaths until one of them returns a truthy value. It could be called `try_keypaths()` or something like that.

Here's how I imagine one would use it:

```
info = {'details' : {'general': { 'description': 'A very neat description' } } }

molto_bene_dict = benedict(info)

try_keys = [
    'something.else.details.general.dscription',
    'unexisting.whatever',
    'details.general.description'
]

molto_bene_dict.try_keypaths(try_keys) == 'A very neat description'
```

If this is something you think it'd fit, I could implement it myself :)
Cheers!

**Comment by fabiocaccamo** [comment]
@emanuelmd eheh, thank you, I'm glad that you like it... I think that this library should deserve more attention.

Your suggestion could be very useful, I will name the method `find`.

**Comment by emanuelmd** [comment]
You already added the thing. Legend!
I guess we can close this issue, thanks.

**Comment by fabiocaccamo** [comment]
@emanuelmd the `find` method will be available in the next release.
