### ISSUE TITLE
wish-list: override parameter to merge function

### ISSUE THREAD

**Issue by Loreton** [fabiocaccamo/python-benedict#24]
I just discovered your "**_benedict_**" package and I'm really enjoying it. It greatly simplifies the handling of dict in python. I am not a professional programmer but I love doing it. I wanted to ask if it is possible to add the **_"override"_** parameter to the **_merge()_** function, perhaps keeping its default value to False. In the meantime, waiting for your reply, I took the liberty of making a copy of merge.py and modifying it accordingly (attached is my solution just as sample).
Thanks very much for your work
Regards
Loreto

[LnMerge.zip](https://github.com/fabiocaccamo/python-benedict/files/5151108/LnMerge.zip)

**Comment by fabiocaccamo** [comment]
@Loreton I'm really glad you enjoy it, thank you!   
You request seems reasonable and backward-compatible, I will add it to the next release!  
PS. the right naming for this is \`**overwrite**\` not `override`.

**Comment by Loreton** [comment]
Overwrite...right. Thank you Fabio.

**Comment by fabiocaccamo** [comment]
Option available in `0.18.2` version.
