### ISSUE TITLE
wrong key-values updates using pointers

### ISSUE THREAD

**Issue by Loreton** [fabiocaccamo/python-benedict#25]
**Python version**
Python 3.6.9

**Package version**
python-benedict (0.18.1)

**Current behavior (bug description)**
I'll try to explain the problem using a simple example.

`my_servers="""

    SERVER:
        S01:
            alias: s01_alias
            ssh_port: s01_port
            host: s01_host
            credentials:
                username: s01_user
                password: s01_passw
            location:
                building: s01_building
                floar: s01_floar
                room: s01_room
`

Creating a benedict dictionary:

    servers=benedict.from_yaml(my_servers)

Creating a couple of pointers (are they pointers???)
      
    s01_ptr=benedict(servers['SERVER.S01'])
    s01_copy=benedict(servers['SERVER.S01'].copy())

Changing some items:
    
     s01_ptr['alias']='ptr_alias'
     s01_ptr['location.building']='ptr_building'
     s01_ptr['credentials.username']='ptr_unsername'

**OUTPUT of the three objects:**

    --- s01_ptr:
    {
        "alias": "ptr_alias",    <--- changed
        "credentials": {
            "password": "s01_passw",
            "username": "ptr_unsername"    <--- changed
        },
        "host": "s01_host",
        "location": {
            "building": "ptr_building",    <--- changed
            "floar": "s01_floar",
            "room": "s01_room"
        },
        "ssh_port": "s01_port"
    }

    --- s01_copy:
    {
        "alias": "s01_alias",    <--- NOT changed
        "credentials": {
            "password": "s01_passw",
            "username": "ptr_unsername"    <--- changed
        },
        "host": "s01_host",
        "location": {
            "building": "ptr_building",    <--- changed
            "floar": "s01_floar",
            "room": "s01_room"
        },
        "ssh_port": "s01_port"
    }

    --- servers:
    {
        "SERVER": {
            "S01": {
                "alias": "s01_alias",    <--- NOT changed
                "credentials": {
                    "password": "s01_passw",
                    "username": "ptr_unsername"    <--- changed
                },
                "host": "s01_host",
                "location": {
                    "building": "ptr_building",    <--- changed
                    "floar": "s01_floar",
                    "room": "s01_room"
                },
                "ssh_port": "s01_port"
            }
        }
    }

**Expected behavior**
As we can see, on the output, all objects are impacted by the changes:
**_s01_ptr_** has been affected by all changes. It's OK
**_s01_copy_**  only the sub-keys out of the root have been affected. It's NOT OK
**_original server object_** just as s01_copy. It's NOT OK

So if they are pointers, the result is wrong, if they are copies the result is wrong. 

Obviously, all this in case I have not made a huge mistake, in which case, I apologize and in any case thank you for the time spent analyzing the problem.

Just another question: what are the differences between the two statements used to create s01_ptr and s01_copy? 
For as I see it, *s01_ptr* should return a *real pointer* (just as in a native python dictionary) while s01_copy should return a copy according to the .copy() suffix. 
At the end what are the differences between the copy() and clone().

Thank You for Your time
Loreto

P.S.: Attached a simple script to re-create the problem.
[Benedict_test02.zip](https://github.com/fabiocaccamo/python-benedict/files/5157108/Benedict_test02.zip)

**Comment by fabiocaccamo** [comment]
@Loreton note that the `copy` method just do a normal `dict.copy` and cast it to `benedict`.  
Could you try to repeat the same test using the standard `dict` please?

**Comment by Loreton** [comment]
Sure...

```json
--- s01_ptr:
{
    "alias": "ptr_alias",   <--- changed
    "credentials": {
        "password": "s01_passw",
        "username": "ptr_unsername"   <--- changed
    },
    "host": "s01_host",
    "location": {
        "building": "ptr_building",   <--- changed
        "floar": "s01_floar",
        "room": "s01_room"
    },
    "ssh_port": "s01_port"
}

--- s01_copy:
{
    "alias": "ptr_alias",   <--- changed
    "credentials": {
        "password": "s01_passw",
        "username": "ptr_unsername"   <--- changed
    },
    "host": "s01_host",
    "location": {
        "building": "ptr_building",   <--- changed
        "floar": "s01_floar",
        "room": "s01_room"
    },
    "ssh_port": "s01_port"
}

--- servers:
{
    "SERVER": {
        "S01": {
            "alias": "ptr_alias",   <--- changed
            "credentials": {
                "password": "s01_passw",
                "username": "ptr_unsername"   <--- changed
            },
            "host": "s01_host",
            "location": {
                "building": "ptr_building",   <--- changed
                "floar": "s01_floar",
                "room": "s01_room"
            },
            "ssh_port": "s01_port"
        }
    }
}
```

     s01_ptr  == s01_copy? True
     s01_ptr  == SERVER[S01]? True
     s01_copy == SERVER[S01]? True

In this case s01_copy is the same as s01_ptr therefore it may not be considered.

Attached simple script to test the problem. You can enter 'benedict' or 'standard' to test one of them.
Regards
loreto
[Benedict_test02a.zip](https://github.com/fabiocaccamo/python-benedict/files/5157364/Benedict_test02a.zip)

**Comment by fabiocaccamo** [comment]
@Loreton thank you, I will test it as soon as possible.

**Comment by fabiocaccamo** [comment]
@Loreton in the test02 you attached, you are not copying the `dict`:  
\`\`\`python  
s01\_ptr=servers\['SERVER'\]\['S01'\]  
s01\_copy=servers\['SERVER'\]\['S01'\] # \<- this should be: s01\_copy=servers\['SERVER'\]\['S01'\].copy()  
\`\`\`

**Comment by fabiocaccamo** [comment]
@Loreton I added a test case for this issue: b9dfedf, it seems that the same error occurs with `dict`

**Comment by Loreton** [comment]
@fabiocaccamo 
You are right.
It was my mistake to include the .copy() example because it might take us out of the main purpose. My purpose is to figure out how to make a pointer using benedict (). If the following statement:

    s01_ptr=benedict(servers['SERVER.S01'])

is the correct one to get a dict_pointer, then we have a different behavior from the standard:

    s01_ptr=servers['SERVER']['S01']

If the statement was not correct, please help me to get the right sintax.
It almost seems that benedict() behaves like a shallow copy.
    
### benedit dict result
    --- s01_ptr:
    {
        "alias": "ptr_alias",
        "credentials": {
            "password": "s01_passw",
            "username": "ptr_unsername"
        },
        "host": "s01_host",
        "location": {
            "building": "ptr_building",
            "floar": "s01_floar",
            "room": "s01_room"
        },
        "ssh_port": "s01_port",
        "z_ptr_add_item": 1224
    }

    --- servers:
    {
        "SERVER": {
            "S01": {
                "alias": "s01_alias",
                "credentials": {
                    "password": "s01_passw",
                    "username": "ptr_unsername"
                },
                "host": "s01_host",
                "location": {
                    "building": "ptr_building",
                    "floar": "s01_floar",
                    "room": "s01_room"
                },
                "ssh_port": "s01_port"
            }
        }
    }

    s01_ptr  == SERVER[S01]? False    <---  benedict dict

### Standard dict result:
    --- s01_ptr:
    {
        "alias": "ptr_alias",
        "credentials": {
            "password": "s01_passw",
            "username": "ptr_unsername"
        },
        "host": "s01_host",
        "location": {
            "building": "ptr_building",
            "floar": "s01_floar",
            "room": "s01_room"
        },
        "ssh_port": "s01_port",
        "z_ptr_add_item": 1224
    }

    --- servers:
    {
        "SERVER": {
            "S01": {
                "alias": "ptr_alias",
                "credentials": {
                    "password": "s01_passw",
                    "username": "ptr_unsername"
                },
                "host": "s01_host",
                "location": {
                    "building": "ptr_building",
                    "floar": "s01_floar",
                    "room": "s01_room"
                },
                "ssh_port": "s01_port",
                "z_ptr_add_item": 1224
            }
        }
    }

    s01_ptr  == SERVER[S01]? True   <---   Standard dict

I hope now it's clearer and I'm sorry for the confusion I may have created.
Loreto

Attached new script without the copy() statement.

[Benedict_test02c.zip](https://github.com/fabiocaccamo/python-benedict/files/5162251/Benedict_test02c.zip)

**Comment by fabiocaccamo** [comment]
@Loreton could you please modify the test that I added in the test suite?

**Comment by Loreton** [comment]
@fabiocaccamo  - Attached the modified tests suite file 


[github_issue_0025_test_case.zip](https://github.com/fabiocaccamo/python-benedict/files/5162751/github_issue_0025_test_case.zip)

**Comment by fabiocaccamo** [comment]
@Loreton the attached test is still not valid, check the difference with the updated test on master.
