### ISSUE TITLE
Strange compatibility issue Spyder 4 vs. PyCharm

### ISSUE THREAD

**Issue by CornyRiegel** [fabiocaccamo/python-benedict#26]
**Python version**
3.8

**Package version**
0.18.2

**Current behavior (bug description)**
When I run this simple code in Spyder 4 (WinPython64-3.8.5.0 ) the package does what it should.
```python
from benedict import benedict

d = benedict('jason.json', format='json')

print(d['embeds[0].author.name'])
```
jason.json file:
```JSON
{
  "content": "Message content",
  "embeds": [
    {
      "title": "Embed1 title",
      "description": "embed 1 description",
      "url": "http://embed1titleurl.com",
      "color": 7506394,
      "author": {
        "name": "embed1 Author name",
        "url": "http://embed1authorurl.com",
        "icon_url": "https://discohook.org/static/discord-avatar.png"
      },
      "footer": {
        "text": "embed 1 footer text",
        "icon_url": "https://discohook.org/static/discord-avatar.png"
      },
      "timestamp": "2020-09-16T22:00:00.000Z"
    },
    {
      "title": "Embed2 title",
      "description": "embed 2 description",
      "url": "http://embed2titleurl.com",
      "color": 7506394,
      "fields": [
        {
          "name": "embed 2 Field 1 name",
          "value": "embed 2 field 1 value"
        }
      ],
      "author": {
        "name": "embed2 Author name",
        "url": "http://embed2authorurl.com",
        "icon_url": "https://discohook.org/static/discord-avatar.png"
      },
      "footer": {
        "text": "embed 2 footer text",
        "icon_url": "https://discohook.org/static/discord-avatar.png"
      },
      "timestamp": "2020-09-07T22:00:00.000Z"
    }
  ]
}
```

Output:
`embed1 Author name`

but when I run this script in PyCharm 2020.2.1 (Community Edition) (Python 3.8) it fails on the import.

```python
Traceback (most recent call last):
  File "C:/Users/TAROX/PycharmProjects/GateControlBot/benedict_test.py", line 3, in <module>
    from benedict import benedict
ImportError: cannot import name 'benedict' from 'benedict' (C:\Users\TAROX\PycharmProjects\GateControlBot\venv\lib\site-packages\benedict\__init__.py)
```

I'm guessing because the package and the class is named exactly the same (btw. BIG NoNo) pycharm is reporting this as an error.
I like the functionality you guys put into this package but I'm currently working inside pycharm and kinda need it working there.

**Comment by fabiocaccamo** [comment]
@CornyRiegel there are many packages names as class methods inside, for example `python-slugify`, could you try please to run `pip install python-slugify` then `from slugify import slugify`.

**Comment by CornyRiegel** [comment]
I found the issue.
PyCharm automatically tried to install the package, but the import isn't called like the package (python-benedict) so it installed BeneDict package instead. After a side-package redo and manually installing the python-benedict package with the optional pip install command it installs all the dependencies as well and now works with the given example up top.

**Comment by fabiocaccamo** [comment]
Good, thank you for the explanaition. I hope you will enjoy this library.
