### ISSUE TITLE
Support defining how input data is loaded (filepath, url or data-string)

### ISSUE THREAD

**Issue by g-v-egidy** [fabiocaccamo/python-benedict#287]
Currently when constructing a benedict object or calling one of the `from_*` functions, the `IODict` class uses the `autodetect_format()` method to automatically determine if the given data is a regular URL, S3 URL, a filepath or a data-string. This is convenient to use because the programmer doesn't have to explicitly specify what kind of data is given and it just does the right thing automatically.

But this also has a downside: if the data sent to benedict is somehow controllable by some untrusted external user, for example when used in a web framework setting, this could be abused in a malicious way. For example by sending a filepath you could let the web framework load a config file that contains secret keys. Or use the URL to access something on the internal network of the web server that would otherwise be protected from outside access.

I suggest to add an optional way to specify how input data is interpreted. The current behaviour of autodetection would stay the default. This option could then be used in the case where the input data comes from untrusted sources.

This is how this could look like:
```
d = benedict("https://localhost:8000/data.json", format="json", open="url")
d.from_json(json_data, open="data")
```
the `open` argument would allow the options "auto"(default), "url", "file", "data".

<a href="https://dashboard.polar.sh/fabiocaccamo/python-benedict/issues/287">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/python-benedict/issues/287/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/python-benedict/issues/287/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@g-v-egidy thank you for reporting this downside.

**Comment by fabiocaccamo** [comment]
@g-v-egidy by upgrading to `0.33.0` version you can do this by using the "sources" argument, you can find more info here: https://github.com/fabiocaccamo/python-benedict#input-sources

**Comment by g-v-egidy** [comment]
Thank you very much for implementing this!
