### ISSUE TITLE
Cast benedict to dict

### ISSUE THREAD

**Issue by abashind** [fabiocaccamo/python-benedict#3]
I’m trying to write benedict object to yaml file, and there is one problem. 
Benedict.to_yaml add “!!python/object/new:benedict.dicts.benedict\ndictitems:” into yaml file.
How can I cast benedict object to “simple” dictionary, which will look like initialy dictionary?
Or how can I write benedict to yaml without “!!python/object/new:benedict.dicts.benedict\ndictitems:” and keypath_separator:\.\n ?

I would like to see in benedict object, member like "python_dict", in order to it would be possible make call like:
>>>my_dict = benedict_object.python_dict
>>>type(my_dict ) is dict
True

**Comment by fabiocaccamo** [comment]
@abashind which `python-benedict` version are you using?

**Comment by abashind** [comment]
@fabiocaccamo I think, current - 0.13.0

**Comment by fabiocaccamo** [comment]
I don't think you have `0.13.0` version, this issue should have already been fixed. 
Please run `pip install python-benedict==0.13.0` and check if your problem persists.

If you need to check an object type:
```python
my_dict = benedict()
if isinstance(my_dict, dict):
   print('Yes, my benedict object is a dict!')
```
or is there something in your request that I'm not understanding? 
If yes, could you explain it better?

**Comment by fabiocaccamo** [comment]
Any update?
