### ISSUE TITLE
Exception when comparing with Protocol classes

### ISSUE THREAD

**Issue by RXminuS** [fabiocaccamo/python-benedict#312]
**Python version**
3.11

**Package version**
0.31.0

**Current behavior (bug description)**
It seems that for some reason when comparing a Benedict with a Protocol class I get thrown a `Protocols with non-method members don't support issubclass()`. I don't have a lot of experience with Protocols so I'm going to need a bit of help figuring out exactly what the problem is.

Also the exception doesn't happen directly from my code instead somewhere deep in Apache Beam when it tries to validate input/output types. Hopefully someone has a good pointer of where to start looking.

**Expected behavior**
I would expect being able to define a protocol type such as 

```
@runtime_checkable
class InputData(Protocol):
   field_a: str
   field_b: int
```

And then have a function such as 
```
def process_data(data: InputData) -> bool:
    return data.field_a == data.field_b
```
Accept a benedict.

At the moment that's maybe a bit overkill but I could see this becoming very nice if more/better type hints are added. Essentially making this a more flexible dataclass that fields etc could be added to.

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/fabiocaccamo/python-benedict/issues/312">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/312/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/312/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@RXminuS thank you for reporting this, could you submit a PR with a failing test case (that should succeeds instead)?

**Comment by fabiocaccamo** [comment]
@RXminuS please, could you try to do the same with a standard `dict` instance to understand if it's a problem of this library or not?

**Comment by RXminuS** [comment]
Will do!

**Comment by fabiocaccamo** [comment]
@RXminuS any feedback?

**Comment by fabiocaccamo** [comment]
@RXminuS even if in `benedict` you can access keys as attributes, they are not real attributes, that's probably the cause of the error.

I will re-open this is you will provide some update.
