### ISSUE TITLE
index filtering in list of dictionaries

### ISSUE THREAD

**Issue by mattiabattaglia** [fabiocaccamo/python-benedict#33]
For my project it was necessary to be able to easily include index filtering. So I had to develop a similar class that enables adressing one or several dictionary entries according to the folowing syntax:
d['key1.key2.(key3.key4==value).key3.key5']=newValue. I think this would be a very pythonic feature that would allow users to work with dictionaries and json-files in a similar way like e.g. with pandas dataframes.
Have you ever thought of including this functionality into python-benedict? If you are interested, I could contribute my code.

**Comment by fabiocaccamo** [comment]
@mattiabattaglia feel free to contribute.

**Comment by fabiocaccamo** [comment]
@mattiabattaglia please check if the new `match` method added in `0.21.0` version solves your problem:
https://github.com/fabiocaccamo/python-benedict#match
