### ISSUE TITLE
Union with assignment operator produces inconsistent results compared to `dict`.

### ISSUE THREAD

**Issue by slava-re** [fabiocaccamo/python-benedict#334]
**Python version**
3.11

**Package version**
0.32.0

**Current behavior (bug description)**
When I use a `|=` operator, the left operand doesn't become reassigned to a union of the two dictionaries as what happens with `dict`s.

```
>>> from benedict import benedict
>>> a = {"a":"a", "b":"b"}
>>> b = {"b":"b", "c":"c"}
>>> a | b
{'a': 'a', 'b': 'b', 'c': 'c'}
>>> ab = benedict(a)
>>> bb = benedict(b)
>>> ab | bb
{'a': 'a', 'b': 'b', 'c': 'c'}
>>> a |= b
>>> a
{'a': 'a', 'b': 'b', 'c': 'c'}
>>> b
{'b': 'b', 'c': 'c'}
>>> a = {"a":"a", "b":"b"}
>>> ab = benedict(a) 
>>> ab |= bb
>>> ab
{'a': 'a', 'b': 'b'}
```

**Expected behavior**
In the last line of the REPL snippet above, `ab` is expected to be `{'a': 'a', 'b': 'b', 'c': 'c'}`.

Using `ab = ab | bb` works around this issue, so this bug is not crucial at all. Just couldn't find this issue reported, so I'm filing this bug.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-benedict/issues/334">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/334/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/334/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@slava-re fixed in `0.32.1` version.
