### ISSUE TITLE
json.dumps no longer works directly with benedict in 0.20.0

### ISSUE THREAD

**Issue by simkimsia** [fabiocaccamo/python-benedict#34]
**Python version**
3.7.7

**Package version**
0.20.0

**Django version**
2.2.15

**Current behavior (bug description)**

Let's say you have a Django 2.2 model that uses the postgres JSONField

```python
from django.contrib.postgres.fields import JSONField
from django.db import models

class SomeModel(models.Model):
    linkage = JSONField(default=dict)
```

When you then do

```python
normal_dict = {'list': {'scope': {'pk': '109'}}
benedict_dict = benedict(normal_dict)

instance = SomeModel.objects.create(linkage=benedict_dict)
retrieved =SomeModel.objects.last() 
```

the `instance.linkage` will definitely still show `{'list': {'scope': {'pk': '109'}}` but `retrieved.linkage` will definitely show `{}`

### What if cast to dict?

if we do this

```python
normal_dict = {'list': {'scope': {'pk': '109'}}
benedict_dict = benedict(normal_dict)

instance = SomeModel.objects.create(linkage=dict(benedict_dict))

```
the `instance.linkage` will definitely still show `{'list': {'scope': {'pk': '109'}}` but `retrieved.linkage` will definitely show `{'list':{}}`

### My workaround

```python

normal_dict = {'list': {'scope': {'pk': '109'}}
benedict_dict = benedict(normal_dict)

sanitized_dict = benedict_dict
if isinstance(benedict_dict, benedict):
    sanitized_dict = json.loads(benedict_dict.to_json())

instance = SomeModel.objects.create(linkage=sanitized_dict)
instance = SomeModel.objects.create(linkage=sanitized_dict)
```

**Expected behavior**
in 0.19.0, this situation does not occur.

But in 0.20.0 this situation occurs. Based on my reading of the changelog it appears that all the methods will auto cast everything to benedict. I guess this is the issue.

Also I would say this goes against the spirit of the line in the readme https://github.com/fabiocaccamo/python-benedict#basics
where it says you can use benedict as a normal dict. That's not true anymore with regards with 0.20.0 and JSONField

**Comment by fabiocaccamo** [comment]
@simkimsia thank you for reporting this. I guess this problem is not related to casting, but to the fact that to keep the pointer to the input dict `benedict` now stores data inside a wrapped dict -> https://github.com/fabiocaccamo/python-benedict/blob/master/benedict/dicts/base/base_dict.py

This should be a completely backward compatibility transparent behavior.  
In case of emergency, there is a new `dict()` method to access the wrapped dict, so you could just do:

```python
normal_dict = {'list': {'scope': {'pk': '109'}}
benedict_dict = benedict(normal_dict)

instance = SomeModel.objects.create(linkage=benedict_dict.dict())
retrieved =SomeModel.objects.last()
```

In any case this is just a workaround, and casting `benedict` to `dict` should work fine.

```python
def test_cast_benedict_to_dict(self):
    b = benedict({
        'a': 1,
        'b': {
            'c': {
                'd': 2,
            },
        },
    })
    d = dict(b)
    self.assertTrue(isinstance(d, dict))
    self.assertEqual(type(d), dict)
    self.assertTrue(b == d)
    self.assertFalse(b is d)
```

It's my intention to keep benedict 100% dict compatible, so we must understand what breaks the django `JSONField` behavior to fix it.

**Could you debug better the cause of this problem?**

**Comment by simkimsia** [comment]
Thank you for prompt reply

@fabiocaccamo 

I try but no promises as this is not high on priority once I have a workaround

Hope you understand

**Comment by fabiocaccamo** [comment]
@simkimsia don't worry, if you find the time, just check what is called by the `JSONField`.

**Comment by simkimsia** [comment]
> if you find the time, just check what is called by the JSONField.

Yes, I will try to do so.

By the way, I see that you made no commits. Yet you cite a method `.dict()` as workaround I don't find in the readme.

Am I mistaken?

![image](https://user-images.githubusercontent.com/245021/93859642-7300bc00-fcf0-11ea-881a-aea10740fedb.png)

**Comment by simkimsia** [comment]
@fabiocaccamo 

I think I found the cause.

THis is my code to test using pytest 3.4.1

```python
import json

from benedict import benedict


"""
doc_string for test_python_class
"""


class TestBenedict:
    """
    doc_string
    """

    def teardown_method(self, test_method):
        pass

    def test_cast_benedict_to_dict(self):
        """
        some doc string
        """
        b = benedict({
            'a': 1,
            'b': {
                'c': {
                    'd': 2,
                },
            },
        })
        d = dict(b)
        assert isinstance(d, dict)
        assert type(d) == dict
        assert b == d
        assert b is not d

    def test_json_dumps_benedict(self):
        """
        some doc string
        """
        b = benedict({
            'a': 1,
            'b': {
                'c': {
                    'd': 2,
                },
            },
        })
        dumped = json.dumps(b)
        print(dumped)
        assert isinstance(dumped, str)
        assert dumped == '{"a": 1, "b": {"c": {"d": 2}}}'


```
This is the 0.20.0 effort when I run `pytest test_benedict.py -s`
![image](https://user-images.githubusercontent.com/245021/93861585-574ae500-fcf3-11ea-85d4-f8d81b142f74.png)

This is the 0.19.0 effort when I run the same command and same test code

![image](https://user-images.githubusercontent.com/245021/93862383-8d3c9900-fcf4-11ea-9cd5-2dc9a579b655.png)


Sorry I know the best way is to create a PR and write a failing test, but I am not sure how to do that in your current setup. 

So it was easier for me to write a failing test as a standalone.

Perhaps you can advise in documentation on how to write failing tests as PR.

**Comment by fabiocaccamo** [comment]
@simkimsia the `dict()` method is used internally and if someone needs to use it, it means that there is some problem, so I intentionally omitted it from the README.

Thank you very much for the test, it's very useful!

**Comment by simkimsia** [comment]
I confirm this works ✅
