### ISSUE TITLE
README Index links don't work on PyPI, only GitHub's markdown renderer

### ISSUE THREAD

**Issue by pushfoo** [fabiocaccamo/python-benedict#340]
### Expected behavior

1. Go to to the [PyPI page](https://pypi.org/project/python-benedict/)
2. Click a link under the Index heading
3. Browser jumps to the topic

### Actual behavior / Replication steps

1. Go to the [PyPI page](https://pypi.org/project/python-benedict/)
2. Click a link under the Index heading
3. Observe: browser does not jump to the heading

### Root cause

The current PyPI builds do not render an HTML ID / name for each heading target for each heading the way GitHub's markdown view does. There is a long-standing issue with PyPA filed related to this: https://github.com/pypa/readme_renderer/issues/169

Some of the comments in the thread ([1](https://github.com/pypa/readme_renderer/issues/169#issuecomment-800728286), [2](https://github.com/pypa/readme_renderer/issues/169#issuecomment-808577486)) mention a workaround: using directly generated HTML anchor tags which PyPI does not strip out.

Since they do not seem like they will fix the markdown renderer soon, perhaps it's possible to automate link target generation for headings as part of the package build?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-benedict/issues/340">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/340/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/340/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@pushfoo do you want to submit a PR?

**Comment by fabiocaccamo** [comment]
@pushfoo I close this because it's more a PyPi bug than a bug of this library README.
