### ISSUE TITLE
Bug:  Passing `data_only=True` into `from_xls()` returns excel formulas instead of cell data values

### ISSUE THREAD

**Issue by kartzke** [fabiocaccamo/python-benedict#355]
**Python version**
Python 3.11.6

**Package version**
python-benedict  0.33.0 

**Current behavior (bug description)**
Using the following code, benedict returns a dictionary with raw cell values, including formulas.   Even though the `data_only=True` kwarg is passed into the constructor. 

```
from benedict import benedict

content = benedict.from_xls("src/data/content.xlsx", sheet="Sheet3", data_only=True)
print(content)
```

![image](https://github.com/fabiocaccamo/python-benedict/assets/713503/d3c76d2e-b9f9-4929-bf0b-b3b684cad334)

**Expected behavior**
I believe `benedict` should return the data values instead of formulas.  So it should return `'formula': 'A2 value is: abc'`  instead of `'formula': '="A2 value is: "&A2'`.   

I'm expecting this because it's an `xlsx` file, which the docs say uses `openpyxl` to fetch the data, and I'm passing the `data_only=True` kwarg into the constructor.  If I try to access this data directly in `openpyxl`, it correctly returns the data values.

If I'm misunderstanding something about the way this is supposed to work, please let me know.  :) 

```
from openpyxl import open

wb = open("src/data/content.xlsx", data_only=True)
for i in wb['Sheet3'].values:
    print(i)
```
![image](https://github.com/fabiocaccamo/python-benedict/assets/713503/7e41c343-8894-4bac-b00f-a65f740d15d4)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-benedict/issues/355">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/355/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/355/pledge.svg">
</picture>
</a>

**Comment by kartzke** [comment]
@fabiocaccamo  Sure thing, the workbook is attached, it has one row of data to demonstrate the issue

[content.xlsx](https://github.com/fabiocaccamo/python-benedict/files/13688035/content.xlsx)

**Comment by fabiocaccamo** [comment]
@kartzke fixed in `0.33.1` version.

**Comment by kartzke** [comment]
Thanks @fabiocaccamo!  I just tested `0.33.1` on my local, the fix works for me.  

I discovered `benedict` last month, it's an awesome python package, great work on it 🙂

**Comment by fabiocaccamo** [comment]
Thanks @kartzke !! I'm really glad you appreciate it!
