### ISSUE TITLE
new_flatten() suggestion

### ISSUE THREAD

**Issue by Loreton** [fabiocaccamo/python-benedict#37]
What do you think about a new method that could combine some of the characteristics of three current methods. 
I would suggest  (after your excellent work for the match method) something like the following:

    r = d.new_flatten(regex_pattern, separator='_', in_keys=True, in_values=True, case_sensitive=False)
         where:
         - search pattern could be imported from the match(...) method
         - arguments could be some of the search(...) parameters
         - returned data could be a dict just like flatten() --> {'full_key_path': value}

It might look like a grep command with a useful output :-)

Thanks and Regards

**Comment by fabiocaccamo** [comment]
@Loreton I don't understand what this method should do, could you explain it better providing an example?

**Comment by Loreton** [comment]
@fabiocaccamo Sure.
I'm trying to use yaml file as configuration file for my little projects.

Also I'm trying to make use of the interpolation concept already present in the python ConfigParser module **${section:option}** which _"enables values to contain format strings which refer to other values in the same section, or values in the special default section"_

To resolve all ${...} I would like to get all the entries, {keypath: value}, containing the pattern.
I was thinking, for example, to flatten() method enriched with further parameters while keeping the original output. 

Example:

    my_dict="""
        common:
            private_key_file: ${env:HOME}/.ssh/id_ed25519
            store:
                path: ${env:script_path}/store
        server_01:
            store: ${common/store/path}
            private_key_file: ${common/private_key_file}
    """

    d = benedict.from_yaml(my_dict)
    _re = re.compile(f'\${(.*?)}')
    flat_data = d.new_method(separator='/', pattern=_re, in_keys=False, in_values=True, case_sensitive=True)
    
    print(flat_data)
    
    {
        'common/private_key_file':    ${env:HOME}/.ssh/id_ed25519
        'common/store/path :          ${env:script_path}/store
        'server_01/private_key_file': ${common/private_key_file}
        'server_01/store':            ${common/store/path}
    }

With the above output is easy to get the variables value and assign it to the right key_path.
It may be that already exists this function, but I missed.
Regards

**Comment by fabiocaccamo** [comment]
I think that this seems to be more a your specific need than a generic feature, but looking at it I think that a new general feature could be to add variables support (with keypath), eg:

```python
d = benedict({
    'a': {
        'b': {
            'c': 'Hello World!',
        },
    },
    'x': '${a/b/c}',
}, keypath_separator='/', variables_enabled=True)

assert d['x'] == 'Hello World!'
```

**Comment by Loreton** [comment]
ok, it doesn't matter, if you think it won't be useful, just ignore the request.
 
Thanks & Regards
