### ISSUE TITLE
benedict.to_json returns empty dict for benedict from generator

### ISSUE THREAD

**Issue by kranonetka** [fabiocaccamo/python-benedict#38]
**Python version**
`Python 3.8.3`

**Package version**
`python-benedict==0.21.0`

**Current behavior (bug description)**
`bededict.to_json` for `benedict` from generator returns `'{}'` instead of json dumped dict

**Expected behavior**
`bededict.to_json` should return actual json dumped dict

**Steps to reproduce**
```python
from benedict import benedict


def gen_dict():
    for k, v in enumerate('abcd'):
        yield k, v


if __name__ == '__main__':
    b = benedict(gen_dict())
    assert b == {0: 'a', 1: 'b', 2: 'c', 3: 'd'}
    assert b.to_json()  ==  '{"0": "a", "1": "b", "2": "c", "3": "d"}'
```
But if recast `benedict` to `dict` and back to `benedict` it works fine
```python
if __name__ == '__main__':
    b = benedict(gen_dict())
    b = benedict(dict(b))
    assert b == {0: 'a', 1: 'b', 2: 'c', 3: 'd'}
    assert b.to_json()  ==  '{"0": "a", "1": "b", "2": "c", "3": "d"}'
```

**Comment by fabiocaccamo** [comment]
You upgrade to `0.21.1` version.
