### ISSUE TITLE
utility method clean does not work for nested dicts

### ISSUE THREAD

**Issue by martinius74** [fabiocaccamo/python-benedict#383]
### Discussed in https://github.com/fabiocaccamo/python-benedict/discussions/382

<div type='discussions-op-text'>

<sup>Originally posted by **martinius74** February 26, 2024</sup>
I was trying to clean my nested dictionaries from any empty string and collections, but somehow, it only considers the root level.
Nested keys are not cleaned.

Looking into the code, the method is using the keys() method.

`def clean(d, strings=True, collections=True):`
`    keys = list(d.keys())`

If we would use the keypaths() method, it would be able to find all nested keys as well:

`def clean(d, strings=True, collections=True):`
`    keys = d.keypaths()`

Would it make sense to change this behaviour? </div>

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-benedict/issues/383">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/383/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/383/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@martinius74 nice catch, I agree this should be the default behaviour, thank you for reporting this.

**Comment by fabiocaccamo** [comment]
@martinius74 you can upgrade to `0.33.2` version.
