### ISSUE TITLE
filter method not taking key_path_separator in consideration

### ISSUE THREAD

**Issue by rbentaarit** [fabiocaccamo/python-benedict#4]
**Python version**
3.7.4

**Package version**
0.14.0

**Current behavior (bug description)**
 d = benedict()
d.keypath_separator = '$' 
 --implementation--
 print (d.keypath_separator)
  d1 = d.filter(lambda k, v: True)
  print (d1.keypath_separator)
> $
> .
This behavior makes me loose the correct structure when I have '.' in the key parameters.
**Expected behavior**
>$
>$

**Comment by fabiocaccamo** [comment]
Thank you for reporting this issue. The same problem affects also all methods that return a new benedict instance.
I will fix this in the next release.

**Comment by fabiocaccamo** [comment]
In the meanwhile you can fix it by doing:
```python
d1 = benedict(d.filter(lambda k, v: True), keypath_separator=d.keypath_separator)
```

**Comment by rbentaarit** [comment]
Thanks for the quick response : )
Unfortunately this will not work because the tree is already generated by the filter function and in my use case I have **'.'** in the keys which will divide them in sub trees before the constructor function.
so my fix for now :
` new_dict = benedict()
  new_dict.keypath_separator = '$'
  keys = list(d.keys())
  for key in keys:
    value = d.get(key, None)
    if True:  
        new_dict[key] = value
  return new_dict`

**Comment by fabiocaccamo** [comment]
I understand the problem, thank you for having explained it better.

**Comment by fabiocaccamo** [comment]
You can install `0.14.1` version.
