### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by pmrowla** [fabiocaccamo/python-benedict#42]
Hi @fabiocaccamo, we are looking to use benedict in https://github.com/iterative/dvc. We need to support conda in DVC and are currently in the process of submitting a conda-forge package for python-benedict. Would you like us add you to the maintainers list for the conda package?  (Maintenance mostly just involves approving auto-generated PRs from conda's bots whenever a new pypi package is released)

https://github.com/conda-forge/staged-recipes/pull/13326

**Comment by fabiocaccamo** [comment]
@pmrowla I'm glad you want to use `benedict` in `dvc`. Sure, feel free to add me to the mainteiners list.

**Comment by pmrowla** [comment]
> Sure, feel free to add me to the mainteiners list.

Done. Whenever you get a chance please add a comment in conda-forge/staged-recipes#13326 noting that you've agreed to be added to the maintainers
