### ISSUE TITLE
Difference between benedict and dict when using tuple[int, ...] as keys.

### ISSUE THREAD

**Issue by burakomurai** [fabiocaccamo/python-benedict#432]
**Python version**
Python 3.11.9

**Package version**
python-benedict==0.33.2

**Current behavior (bug description)**
Difference between dict() and benedict() with a specific case.

d1 = {}
d2 = benedict.benedict()

d1[(0, 0, 1)] = "a"
d2[(0, 0, 1)] = "a"

print(d1, "\n", d2)
# {(0, 0, 1): 'a'}
# {0: [[None, 'a']]}

**Expected behavior**
Same as the dict() output.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-benedict/issues/432">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/432/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/432/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@burakomurai fixed in `0.34.0` version.
