### ISSUE TITLE
Bug: Many serious TOML parsing/loading bugs caused by underlying toml library, consider switching?

### ISSUE THREAD

**Issue by pirate** [fabiocaccamo/python-benedict#439]
Thanks so much for building python-benedict, it's really awesome!

So unfortunatley the underlying TOML library https://github.com/uiri/toml used by benedict has a bunch of long-time outstanding bugs that break parsing/loading and generally make it unsafe to load->dump->load the same string.

For example, you cannot dump any dict containing escape sequences without it throwing an exception: 

```python
>>> benedict({
	"reset": "\033[00;00m",
	"lightblue": "\033[01;30m",
}).to_toml()

...
File ~/test/.venv/lib/python3.11/site-packages/toml/encoder.py:113, in _dump_str(v)
    111     else:
    112         joiner = "u00"
--> 113     v = [v[0] + joiner + v[1]] + v[2:]
    114 return unicode('"' + v[0] + '"')

IndexError: list index out of range
```

But thats not it, there are many other fairly major string escaping, quoting, and parse/dump cycle inconsistency bugs that have bitten other projects using `uiri/toml`:
- https://github.com/uiri/toml/issues/441
- https://github.com/uiri/toml/issues/437
- https://github.com/uiri/toml/issues/415
- https://github.com/uiri/toml/issues/387
- https://github.com/uiri/toml/issues/322
- https://github.com/uiri/toml/issues/404
- https://github.com/uiri/toml/issues/230
- https://github.com/uiri/toml/issues/280
- https://github.com/uiri/toml/issues/201
- https://github.com/uiri/toml/issues/270
- https://github.com/uiri/toml/issues/170
- https://github.com/uiri/toml/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+escape

Almost all of these are 2yr+ old, indicating they're probably not going to all get fixed anytime soon without significant increase in velocity. No harm no foul, it's open source we can't demand they go faster and they don't owe us anything, but maybe benedict could consider a different library with fewer major outstanding parser consistency issues?

Is benedict open to switching to a library without these issues? Maybe one of these:  
- https://github.com/hukkin/tomli
- https://github.com/python-poetry/tomlkit
- https://github.com/hukkin/tomli-w

I'll chip in $20 towards the work to make the switch if it's an option ⬇️ 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-benedict/issues/439">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/439/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/439/pledge.svg">
</picture>
</a>

**Comment by pirate** [comment]
After looking more into the other options unfortunately they are worse in other ways, for example they can barely handle a fraction of the types that `uiri/toml` supports :/

I guess we are stuck writing a custom `TomlEncoder` class to work around the bugs for now.

You're welcome to close this issue 🤷, up to you.

**Comment by fabiocaccamo** [comment]
@pirate thank you for reporting this problem.

Actually, for decoding `toml` on `Python >= 3.11`, the `tomlib` standard lib is used: 
https://github.com/fabiocaccamo/python-benedict/blob/main/benedict/serializers/toml.py#L10

I think it would be cool to improve TOML support, would you like to submit a PR with a list of failing test cases (that should succeed with the perfect library)? 
So it would be much easier to test other TOML libraries or doing fixes in a different way.

**Comment by fabiocaccamo** [comment]
@pirate is it in your plans to submit a PR for this?

**Comment by pirate** [comment]
I think if you are using one of the big toml libraries it's not worth trying to patch its behavior on top within benedict. Here is a good test suite for TOML parsing though: https://github.com/toml-lang/toml-test

You can leave it up to end users to figure out a workaround if they really need one (e.g. my `CustomTOMLEncoder` above). I just wanted to document this issue so people could find it via Google if they have the same problem and wondered teh cause.

**Comment by fabiocaccamo** [comment]
@pirate totally agree, it would make more sense to fix these issue at toml lib level.
