### ISSUE TITLE
Cannort import benedict

### ISSUE THREAD

**Issue by gschoenberger** [fabiocaccamo/python-benedict#44]
**Python version**
3.8

**Package version**
0.22.2

**Current behavior (bug description)**
>>> from benedict import benedict
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name 'benedict' from 'benedict' (unknown location)

**Expected behavior**
It should be possible to import and use benedict.

** Additional pip information
$ pip show python-benedict 
Name: python-benedict
Version: 0.22.2
Summary: python-benedict is a dict subclass with keylist/keypath support, I/O shortcuts (base64, csv, json, pickle, plist, query-string, toml, xml, yaml) and many utilities... for humans, obviously.
Home-page: https://github.com/fabiocaccamo/python-benedict
Author: Fabio Caccamo
Author-email: fabio.caccamo@gmail.com
License: MIT

**Comment by fabiocaccamo** [comment]
This is really strange, you are the first one reporting this issue.
Could you send please a PR containing a test which should succeed but fails?

**Comment by gschoenberger** [comment]
I found the problem!
PyCharm installed the wrong benedict: https://pypi.org/project/BeneDict/
PyCharm installed "BeneDict" with "pip install benedict" automatically when using the import statement: "from benedict import benedict"
But as you wrote in the docs, you have to run "pip install python-benedict"...

**Comment by fabiocaccamo** [comment]
I understand... maybe it would be useful to report this issue to `PyCharm`.

**Comment by Vermyndax** [comment]
Interestingly, I'm having this exact same problem. I verified that I installed python-benedict, unlike the person above, but it's still not finding the library.

**Comment by fabiocaccamo** [comment]
@Vermyndax are you using PyCharm too?

**Comment by Vermyndax** [comment]
No, I'm using just regular old pip. Even more odd... if I run this from a virtualenv, Benedict isn't recognized. If I come out of the venv and use system packages, it works fine. Both were installed with pip.

**Comment by fabiocaccamo** [comment]
@Vermyndax also I use pip with virtualenv, have you installed the right package and you are importing it correctly? 
- `pip install python-benedict`
- `from benedict import benedict`

**Comment by ddl-tanner-green** [comment]
pip uninstall python-benedict
pip uninstall benedict
pip install python-benedict

**Comment by stanleyjs** [comment]
Having this problem in 2023. I tried doing what @ddl-tanner-green suggested and this did not fix the broken install

**Comment by fabiocaccamo** [comment]
What happens if you follow these steps?

https://github.com/fabiocaccamo/python-benedict#testing

**Comment by shalomb** [comment]
what worked for me was to downgrade and upgrade back to same version? hmm

```shell
$ python3 -c 'from benedict import benedict^J'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'benedict' from 'benedict' (unknown location)

$ pip list | grep -i benedict
python-benedict    0.32.1

$ pip install python-benedict==0.30

$ python3 -c 'from benedict import benedict^J'

$ pip install -U python-benedict

$ python3 -c 'from benedict import benedict^J'
```
