### ISSUE TITLE
`from_json` method returns empty for valid input

### ISSUE THREAD

**Issue by GamesmenJordan** [fabiocaccamo/python-benedict#440]
**Python version**
3.12.6

**Package version**
0.33.2

**Current behavior (bug description)**
Different results when using `benedict.from_json(f.read())` compared to `benedict(json.load(f))` on the same file. Using the `from_json` method returns empty dict.

```json
{
    "key_alpha": {
        "key_beta": "beta-value",
        "key_charlie": "charlie-value"
    },
    "key_delta": "delta-value"
}
```

```python
import json
from benedict import benedict

with open('test.json') as f:
    # Variations of this including from_json('test.json') also behave the same
    data = f.read()
    benedict_from_json = benedict()
    benedict_from_json.from_json(data)
    print("benedict_from_json test\n---------------------")
    print(benedict_from_json)

with open('test.json') as f:
    data = f.read()
    benedict_json_load = benedict(json.loads(data))
    print("benedict_json_load test\n---------------------")
    print(benedict_json_load)

print("End test")
```

```
benedict_from_json test
---------------------
{}
benedict_json_load test
---------------------
{'key_alpha': {'key_beta': 'beta-value', 'key_charlie': 'charlie-value'}, 'key_delta': 'delta-value'}
```

**Expected behavior**
Both should result in the same object: `{'key_alpha': {'key_beta': 'beta-value', 'key_charlie': 'charlie-value'}, 'key_delta': 'delta-value'}`

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/python-benedict/issues/440">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/440/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/python-benedict/issues/440/pledge.svg">
</picture>
</a>

**Comment by GamesmenJordan** [comment]
This seems like it's too obvious of an issue that it should have been called out already, so if the fault is mine and I've done something stupid forgive me but as I understand it from the documentation I have used the method correctly.

**Comment by fabiocaccamo** [comment]
@GamesmenJordan thank you for reporting this, I check and eventually fix it as soon as possible.

**Comment by fabiocaccamo** [comment]
@GamesmenJordan `from_json` is a classmethod, you should use it like `benedict.from_json`, instead you are using is like an instance method.
