### ISSUE TITLE
Update or insert

### ISSUE THREAD

**Issue by LinnaViljami** [fabiocaccamo/python-benedict#45]
# Problem description

The current merge() function is awesome but can not handle situation where we want UPDATE OR IF NECESSARY extend nested dictionary/list with  new value/path.

Let me deliver an example:
```
test_object = {
    "foo": [{"bar": {"rer" : "value"}}]
}

new_key_value_object = {
'foo': [{'bar': {'test': 'update'}}]
}

# I would want to update or insert new value to path `foo[0].bar.test` depending on if the path exist or not.

# With overwrite true:
> test.object.merge(new_key_value_object, overwrite=True) 
> result:  {'foo': [{'bar': {'test': 'update'}}]}

# With overwrite false:
> test.object.merge(new_key_value_object, overwrite=False) 
> result:  {"foo": [{"bar": {"rer" : "value"}}]}

# Desired result:
 {
"foo": [
                  {"bar": {
                       "rer" : "value",
                       "test": "update"
                            }
                  }
         ]
}
```
Generally I would want function which insert or update value to path, but not override paths. If paths are missing we add the new path but not override anything but the final value

# Possible solutions
Create insert_or_update(path, newValue) method
Add new parameters to merge() function to support this feature.

**Comment by LinnaViljami** [comment]
I could also impelement this myself and be part of the project :)

**Comment by fabiocaccamo** [comment]
@LinnaViljami thank you for this suggestion. What you are asking for is pretty clear and already planned.

**Comment by LinnaViljami** [comment]
Thanks for quick answer @fabiocaccamo . Is there some plans about when and how this feature may be implemented? Is somebody already working on it, or are there any ideas which kind of method/addition would fit well to this project?

**Comment by fabiocaccamo** [comment]
@LinnaViljami you can upgrade to `0.22.4` version and check the new `concat` option in the `merge` method.

**Comment by LinnaViljami** [comment]
Awesome Job! Thank you! 😊

ti 22. jouluk. 2020 klo 14.25 Fabio Caccamo <notifications@github.com>
kirjoitti:
