### ISSUE TITLE
filter and modify list of dicts

### ISSUE THREAD

**Issue by quancore** [fabiocaccamo/python-benedict#47]
So I have a list of dicts like this (this dict could be in nested dict as well):
`guilds = [{"ID":1, "Name":"x"}, {"ID":2, "Name":"y"}]`

I want to modify the value of the `Name` key in the dict which `ID` is 1. I could not find how can I do that with the library.

**Comment by fabiocaccamo** [comment]
You need to iterate over the dicts list and change the value if your condition is satisfied.

How would you expect to do it using this library?

**Comment by quancore** [comment]
Actually, I already see a related issue here: #33 
Some methods to combine key path and filters would be perfect like "key1.key2.['ID' == val].Name", so if the result is a shallow copy, I can modfiy.

**Comment by fabiocaccamo** [comment]
@quancore actually this is not possible. 

This request seems to go in the direction of add `xpath` support, what do you think about it?

**Comment by quancore** [comment]
Yes, all the roads going to a capable path conversion like XPath.

**Comment by fabiocaccamo** [comment]
I close this issue moving it to #67.
