### ISSUE TITLE
get doesn't work when the key is a list with one element.

### ISSUE THREAD

**Issue by mathiasrabe** [fabiocaccamo/python-benedict#5]
**Python version**
3.7.4

**Package version**
0.14.0

**Current behavior (bug description)**
I tried the following:
```
from benedict import benedict

key = ['1', '2']
dictionary = {'1' : {'2' : 'two'}}
d = benedict(dictionary)
print(d.get(key))

key = ['1']
dictionary = {'1' : 'one'}
d = benedict(dictionary)
print(d.get(key))
```
'two' will be printed but 'one' not. I get an type error: TypeError: unhashable type: 'list'

**Expected behavior**
I expected that the last command will print 'one'.

**Comment by fabiocaccamo** [comment]
@mathiasrabe thanks for reporting this, I will fix it as soon as possible.

**Comment by fabiocaccamo** [comment]
You can install `0.14.1` version.
