### ISSUE TITLE
Clean values in lists

### ISSUE THREAD

**Issue by sommelon** [fabiocaccamo/python-benedict#51]
Is there a way to clean all values, including those that are in a list with one method? If not it would be nice to have.

**Comment by fabiocaccamo** [comment]
@sommelon actually the clean method doesn't clean recursively.

**Comment by sommelon** [comment]
@fabiocaccamo oh, I see, I overlooked it. Are you planning to add it in the future?

**Comment by fabiocaccamo** [comment]
@sommelon actually I'm quite busy, I will add it when I will need it on an existing project.
