### ISSUE TITLE
Original object is getting updated in the `merge` operation

### ISSUE THREAD

**Issue by saveshodhan** [fabiocaccamo/python-benedict#52]
**Python version**
3.8.5

**Package version**
0.23.2

**Current behavior (bug description)**
The `benedict` object when merged with another `dict` also updates the original object, even though both point to different memory locations.
In the example below, `a` was passed to `benedict` and stored in `b`, and even though both have different memory addresses, both of these are updated in the `merge` operation:
```python
>>> from benedict import benedict
>>> 
>>> a = {'1': {'words': 'one'}, '2': {'words': 'two'}}
>>> 
>>> b = benedict(a)
>>> 
>>> a is b
False
>>> 
>>> a['1'] is b['1']
False
>>> 
>>> 
>>> b.merge({'1': {'val': 1}})
>>> 
>>> b
{'1': {'words': 'one', 'val': 1}, '2': {'words': 'two'}}
>>> 
>>> a
{'1': {'words': 'one', 'val': 1}, '2': {'words': 'two'}}
>>> 
>>> b.merge({'2': {'words': 'due'}})
>>> 
>>> b
{'1': {'words': 'one', 'val': 1}, '2': {'words': 'due'}}
>>> a
{'1': {'words': 'one', 'val': 1}, '2': {'words': 'due'}}
>>> 
```

**Expected behavior**
The `merge` operation should not update the original object (`a` in this case)

**Comment by fabiocaccamo** [comment]
@saveshodhan if you initialize benedict with an existing dict, it will keep the pointer to the original dict, you can read more about this in #32.

If you want to preserve the original instance you can just clone the benedict instance.
