### ISSUE TITLE
How would I search and replace using an arbitrary function?

### ISSUE THREAD

**Issue by jtlz2** [fabiocaccamo/python-benedict#55]
Many thanks for such awesome code - super helpful!

I would now like to search and replace fields of a certain type within an arbitrarily-nested dictionary (including sets, lists, more dicts etc.), the aim being to replace those fields with primitive types so I can serialize the dictionary.

I can see how to `search` and `filter`, but not how to `apply`?

How would you achieve this using `python-benedict`?

Or would you recommend another route?

Many thanks once again

**Comment by fabiocaccamo** [comment]
@jtlz2 thanks! I'm glad you find it useful.

You should be able to do that using the `search` or the `traverse` method, could you show your dict please?

**Comment by fabiocaccamo** [comment]
@jtlz2 any feedback?
