### ISSUE TITLE
Merge and one line operation

### ISSUE THREAD

**Issue by sshishov** [fabiocaccamo/python-benedict#56]
### Currently, to do a merge, we should have multiple lines of code which is not what users like.

Let's assume this example:
```python
dict_a = {'a': 1, 'b': 2}
dict_b = {'c': 3, 'd': 4}
dict_c = benedict()
dict_c.merge(dict_a, dict_b)
```
It would be nice to simplify 2 last lines like this:
```python
dict_a = {'a': 1, 'b': 2}
dict_b = {'c': 3, 'd': 4}
dict_c = benedict.merge(dict_a, dict_b)
```
And all the logic about creation of new dictionary and merging it would be encapsulated.

### Standard python implementation
Standard `dict's` method update suffers the same way that is why users come up with:
```python
dict_c={**dict_a, **dict_b}
```
or similar approaches.

### What is happening now
```python
dict_c = benedict.merge(dict_a, dict_b)
```
Returning null and modifying `dict_a` what is useless. If I want to change `dict_a`, I can type:
```python
dict_a.merge(dict_b)
```
But if I would like to create new dict from merging 2 others, there is no one-line solution.

**Comment by fabiocaccamo** [comment]
**The standard python implementation doesn't support deep merge.**

> But if I would like to create new dict from merging 2 others, there is no one-line solution.

This is wrong, because you can do this:
```python
dict_c = dict_a.clone().merge(dict_b)
```

**Comment by sshishov** [comment]
@fabiocaccamo you are right! Thank you for the hint!
