### ISSUE TITLE
json.dumps broken 24.0

### ISSUE THREAD

**Issue by alexespencer** [fabiocaccamo/python-benedict#57]
**Python version**
3.8

**Package version**
24.0

**Current behavior (bug description)**
Passing a benedict dictionary into json.dumps() returns an empty dictionary if you initialise benedict on an empty dict
```
test3 = benedict({})
test3.set('a', 1)
print(test3)
print(json.dumps(test3))
```

![image](https://user-images.githubusercontent.com/7407677/127334542-3cc1f61e-89a2-4e07-a021-d6d36224187c.png)

**Expected behavior**
`json.dumps(benedict_dict)` should work as normal. Work around is to call `json.dumps(benedict_dict.dict())`

**Comment by alexespencer** [comment]
It looks like json.dumps() works if initialised on non-empty dict. Maybe a new unit test is required too?

**Comment by fabiocaccamo** [comment]
@alexespencer thank you for reporting this.

**Comment by fabiocaccamo** [comment]
@alexespencer You can upgrade to `0.24.1` version. 

It seems that python doesn't keep the pointer to an empty dict, you can test it yourself:
```python
r = {}
d = benedict(r)
d.set('a', 1)
print(d)
print(json.dumps(d)) # -> empty 

r = {'a': None}
d = benedict(r)
d.set('a', 1)
print(d)
print(json.dumps(d)) # -> {'a': 1}
```

**Comment by alexespencer** [comment]
Great stuff, thank you.
