### ISSUE TITLE
All the mutators should update both the superclass and the `._dict`

### ISSUE THREAD

**Issue by simkimsia** [fabiocaccamo/python-benedict#61]
Based on the conversation started by @skshetry

> This will keep the data in two places though.

_Originally posted by @skshetry in https://github.com/fabiocaccamo/python-benedict/pull/60#discussion_r684717721_

I have studied the various instance methods inside BaseDict.py

My conclusions/hypotheses/assumptions:

1. A two dataset solution is assumed.
2. Therefore, all mutator methods (such as `__setitem__` and `clear`, etc) need to update both the superclass dict and the `._dict`. 
3. All accessor methods (such as `__len__`, etc) should access the `._dict` if there's a `._pointer`. Otherwise, access the superclass dict.

If my assumption (pt 1) is wrong, then I will close this issue.

If my assumption is right, but my reasoning is wrong, I will also close this issue.

If my assumption and reasoning are right, then I like to recommend code changes to all mutator methods inside BaseDict class as recommended in pt 2.

**Comment by fabiocaccamo** [comment]
You can upgrade to `0.24.2`.
