### ISSUE TITLE
.flatten() and .unflatten() dont respect keypath_separator

### ISSUE THREAD

**Issue by Dorianux** [fabiocaccamo/python-benedict#63]
**Python version**
3.9

**Package version**
0.24.2

**Current behavior (bug description)**

>>> from benedict import benedict
>>> bd = benedict({"a_b":1,"a_c":{"a":1,"b":2}},keypath_seperator=None)
>>> bdf = bd.flatten()
>>> bdf.unflatten()
{'a': {'b': 1, 'c': {'a': 1, 'b': 2}}}

or 

>>> bd = benedict({"a_b":1,"a_c":{"a":1,"b":2}},keypath_seperator=".")
>>> bdf = bd.flatten()
>>> bdf.unflatten()
{'a': {'b': 1, 'c': {'a': 1, 'b': 2}}}

**Expected behavior**

>>> bd = benedict({"a_b":1,"a_c":{"a":1,"b":2}},keypath_seperator=".")
>>> bdf = bd.flatten()
>>> bdf.unflatten()
{"a_b":1,"a_c":{"a":1,"b":2}}

**remark**

benedict is a very cool package, thnx

**Comment by fabiocaccamo** [comment]
I'm pretty sure that using the `keypath_separator` as flatten separator creates some conflict, but I understand the problem you are reporting and you are right, maybe a double underscore `__` could solve both problems.

**Comment by Dorianux** [comment]
sorry, i dont understand.
you mean the examples i provided are already behaving correct?

the problem i have is, that my keys contain a "_".
i just want no changes to my keys, how can i achive that?

Both keypath_seperator=None and keypath_seperator="__" result in changed keynames for flatten and unflatten. 

>>> bd = benedict({"a_b":1,"a_c":{"a":1,"b":2}},keypath_seperator="__")
>>> bd.flatten().unflatten()
{'a': {'b': 1, 'c': {'a': 1, 'b': 2}}}

**Comment by Dorianux** [comment]
oh, i just found that flatten() and unflatten() accept an separator argument.

sorry for the buzz! 

>>> bd = benedict({"a_b":1,"a_c":{"a":1,"b":2}})
>>> bd.flatten(separator=".").unflatten(separator=".")
{"a_b":1,"a_c":{"a":1,"b":2}}

works as expected!
