### ISSUE TITLE
Tuple index support

### ISSUE THREAD

**Issue by Darkdragon84** [fabiocaccamo/python-benedict#66]
Great library! There is the great feature for list index support `loc = d['results[0].locations[-1]']`, where `results` and `locations` are lists. I would love to see the same support for tuples, i.e. the above should also work for e.g. `d={"results": [{"locations": (1,2,3)}, {"locations": (4,5,6)}, {"locations": (7,8,9)}, {"locations": (10,11,12)}]}`. Is there a specific reason why tuples are not supported? I am happy to submit a PR myself if you can give me pointers where I need to change code besides `_get_keylist_for_value` and `__getitem__`.

**Comment by fabiocaccamo** [comment]
@Darkdragon84 you can upgrade to `0.24.3` version.
