### ISSUE TITLE
List embedded on dictionary

### ISSUE THREAD

**Issue by dhernandezgt** [fabiocaccamo/python-benedict#9]
Hi Fabio, 
it is a good package and useful for dictionary nested.  The suggestion is methods for fetching data from dictionary embedded on list, returning a list or individual value.

for example:
`items.key1` return `[val1,val1, ... ,val1]` from each key1. 
`items.key1[x]` return `val1` from x.
`items.key1[x].key3[x].key71[x]` return `[val1,val3,val71]` from x.
 
I expect that my suggestion seem an improvement on package for you.

best regards

DH

[dict structure.txt](https://github.com/fabiocaccamo/python-benedict/files/4209388/dict.structure.txt)

**Comment by fabiocaccamo** [comment]
@dhernandezgt I have not understood very well what you would like to be able to do, and the data-structure file is empty, could you provide a real case example?

**Comment by dhernandezgt** [comment]
Hi Fabio,

it attached and example file.  I continue checking different methods that
are useful but I don't find

items.key01 return [PReJPJ0UUCQ,PReP99YQPU0R, ... ,PRe99VU28YJC] from each
dictionary in items.
items.key01[0] return PReJPJ0UUCQ or items.key01[1] return  PReP99YQPU0R or
last element in list items.key01[-1] return  PRe99VU28YJC
return items.key01[1].expLevel[1].campo[1]['id'] return
[PReP99YQPU0R,12,54000016] from element 1 in items.

**Comment by fabiocaccamo** [comment]
@dhernandezgt you can do it in two ways:
-   Using keypath:
```python
return items["key01[1].expLevel[1].campo[1].id"]
```
-   Using keylist:
```python
return items["key01", 1, "expLevel", 1, "campo", 1, "id"]
```
